name: deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install
        run: yarn install

      - name: Start
        run: yarn start

      - name: Start
        run: yarn emojis
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

      - name: deploy
        run: |
          cd dist
          git config --global user.name "$user_name"
          git config --global user.email "$user_email"
          git init
          git add -A
          git commit -m "${{ github.event.head_commit.message }}"
          git push -f https://_:"$token"@github.com/${{ github.event.repository.full_name }}.git master:assets
        shell: bash
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          user_name: GitHub Action
          user_email: action@github.com
